"""Vault index generator — compiler step 3.

Rebuilds the three index notes for a workspace vault:
  - vault/{workspace_id}/indexes/sources-index.md
  - vault/{workspace_id}/indexes/entities-index.md
  - vault/{workspace_id}/indexes/tags-index.md

Index notes are fully compiler-owned (type: index). They are always overwritten
on rebuild — do not hand-edit them (per frontmatter-schema.md invariant 5).

Inputs:
  - workspace_vault_dir: Path to vault/{workspace_id}/

Outputs:
  - Three index .md files on disk.
  - IndexRebuildResult with entry counts and paths.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import yaml

from atlas_worker.compiler.vault_writer import parse_frontmatter, render_frontmatter

logger = logging.getLogger(__name__)

COMPILER_VERSION = "worker/compiler-v1"
_FRONTMATTER_RE = re.compile(r"^---\r?\n(.*?)\r?\n---\r?\n", re.DOTALL)


# ---------------------------------------------------------------------------
# Data contracts
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class IndexRebuildResult:
    workspace_id: str
    sources_index_path: Path
    entities_index_path: Path
    tags_index_path: Path
    source_count: int
    entity_count: int
    tag_count: int


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _read_frontmatter(path: Path) -> dict:
    try:
        raw = path.read_text(encoding="utf-8")
        fm, _ = parse_frontmatter(raw)
        return fm
    except OSError:
        return {}


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _index_frontmatter(
    title: str,
    slug: str,
    workspace_id: str,
    index_kind: str,
    entry_count: int,
    generated_at: str,
) -> dict:
    return {
        "title": title,
        "slug": slug,
        "type": "index",
        "index_kind": index_kind,
        "created": generated_at,
        "updated": generated_at,
        "workspace_id": workspace_id,
        "tags": [f"index/{index_kind}", "status/auto"],
        "generated_at": generated_at,
        "generated_by": COMPILER_VERSION,
        "entry_count": entry_count,
    }


def _write_index(path: Path, frontmatter: dict, body: str) -> None:
    """Always overwrite index notes — they are compiler-owned."""
    path.parent.mkdir(parents=True, exist_ok=True)
    content = render_frontmatter(frontmatter) + body
    path.write_text(content, encoding="utf-8")
    logger.info("wrote index: %s (%d entries)", path.name, frontmatter.get("entry_count", 0))


# ---------------------------------------------------------------------------
# Sources index
# ---------------------------------------------------------------------------


def _build_sources_index(
    workspace_vault_dir: Path,
    workspace_id: str,
    generated_at: str,
) -> tuple[Path, int]:
    sources_dir = workspace_vault_dir / "sources"
    rows: list[tuple[str, str, str, str]] = []  # (title, date, tags, link)

    if sources_dir.exists():
        for md in sorted(sources_dir.glob("*.md")):
            fm = _read_frontmatter(md)
            if not fm:
                continue
            title = fm.get("title", md.stem)
            slug = fm.get("slug", md.stem)
            date = fm.get("published_at") or fm.get("created", "")[:10]
            tags = ", ".join(fm.get("tags") or [])
            rows.append((title, date, tags, f"[[sources/{slug}]]"))

    lines = [
        "# Sources Index\n",
        f"*Auto-generated by compiler. {len(rows)} source(s). Last rebuilt: {generated_at}.*\n",
        "\n| Title | Date | Tags | Link |\n",
        "|-------|------|------|------|\n",
    ]
    for title, date, tags, link in rows:
        lines.append(f"| {title} | {date} | {tags} | {link} |\n")

    body = "".join(lines)
    path = workspace_vault_dir / "indexes" / "sources-index.md"
    fm = _index_frontmatter(
        title="Sources Index",
        slug="sources-index",
        workspace_id=workspace_id,
        index_kind="sources",
        entry_count=len(rows),
        generated_at=generated_at,
    )
    _write_index(path, fm, body)
    return path, len(rows)


# ---------------------------------------------------------------------------
# Entities index
# ---------------------------------------------------------------------------


def _build_entities_index(
    workspace_vault_dir: Path,
    workspace_id: str,
    generated_at: str,
) -> tuple[Path, int]:
    entities_dir = workspace_vault_dir / "entities"
    rows: list[tuple[str, str, int, str]] = []  # (name, kind, source_count, link)

    if entities_dir.exists():
        for md in sorted(entities_dir.glob("*.md")):
            fm = _read_frontmatter(md)
            if not fm:
                continue
            name = fm.get("title", md.stem)
            slug = fm.get("slug", md.stem)
            kind = fm.get("entity_kind", "unknown")
            prov = fm.get("provenance") or {}
            source_count = len(prov.get("source_ids") or [])
            rows.append((name, kind, source_count, f"[[entities/{slug}]]"))

    lines = [
        "# Entities Index\n",
        f"*Auto-generated by compiler. {len(rows)} entity/entities. Last rebuilt: {generated_at}.*\n",
        "\n| Name | Kind | Sources | Link |\n",
        "|------|------|---------|------|\n",
    ]
    for name, kind, source_count, link in rows:
        lines.append(f"| {name} | {kind} | {source_count} | {link} |\n")

    body = "".join(lines)
    path = workspace_vault_dir / "indexes" / "entities-index.md"
    fm = _index_frontmatter(
        title="Entities Index",
        slug="entities-index",
        workspace_id=workspace_id,
        index_kind="entities",
        entry_count=len(rows),
        generated_at=generated_at,
    )
    _write_index(path, fm, body)
    return path, len(rows)


# ---------------------------------------------------------------------------
# Tags index
# ---------------------------------------------------------------------------


def _build_tags_index(
    workspace_vault_dir: Path,
    workspace_id: str,
    generated_at: str,
) -> tuple[Path, int]:
    tag_to_notes: dict[str, list[str]] = {}

    for md in sorted(workspace_vault_dir.rglob("*.md")):
        # Skip indexes themselves.
        if md.parent.name == "indexes":
            continue
        fm = _read_frontmatter(md)
        if not fm:
            continue
        slug = fm.get("slug", md.stem)
        note_type = fm.get("type", "unknown")
        folder = note_type + "s"
        wikilink = f"[[{folder}/{slug}]]"
        for tag in fm.get("tags") or []:
            tag_to_notes.setdefault(tag, []).append(wikilink)

    # Group by namespace prefix.
    namespaces: dict[str, dict[str, list[str]]] = {}
    for tag, notes in sorted(tag_to_notes.items()):
        prefix = tag.split("/")[0] if "/" in tag else "other"
        namespaces.setdefault(prefix, {})[tag] = notes

    lines: list[str] = [
        "# Tags Index\n",
        f"*Auto-generated by compiler. {len(tag_to_notes)} tag(s). Last rebuilt: {generated_at}.*\n",
    ]
    for ns in sorted(namespaces):
        lines.append(f"\n## {ns}\n\n")
        for tag in sorted(namespaces[ns]):
            note_links = ", ".join(namespaces[ns][tag])
            lines.append(f"- `{tag}` — {note_links}\n")

    body = "".join(lines)
    path = workspace_vault_dir / "indexes" / "tags-index.md"
    fm = _index_frontmatter(
        title="Tags Index",
        slug="tags-index",
        workspace_id=workspace_id,
        index_kind="tags",
        entry_count=len(tag_to_notes),
        generated_at=generated_at,
    )
    _write_index(path, fm, body)
    return path, len(tag_to_notes)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def rebuild_indexes(workspace_vault_dir: Path) -> IndexRebuildResult:
    """Rebuild all three index notes for a workspace vault.

    Always overwrites existing index notes — they are compiler-owned.

    Args:
        workspace_vault_dir: Absolute path to vault/{workspace_id}/

    Returns:
        IndexRebuildResult with paths and entry counts.
    """
    workspace_id = workspace_vault_dir.name
    generated_at = _now()

    sources_path, source_count = _build_sources_index(
        workspace_vault_dir, workspace_id, generated_at
    )
    entities_path, entity_count = _build_entities_index(
        workspace_vault_dir, workspace_id, generated_at
    )
    tags_path, tag_count = _build_tags_index(
        workspace_vault_dir, workspace_id, generated_at
    )

    logger.info(
        "indexes rebuilt for workspace=%s: %d sources, %d entities, %d tags",
        workspace_id,
        source_count,
        entity_count,
        tag_count,
    )

    return IndexRebuildResult(
        workspace_id=workspace_id,
        sources_index_path=sources_path,
        entities_index_path=entities_path,
        tags_index_path=tags_path,
        source_count=source_count,
        entity_count=entity_count,
        tag_count=tag_count,
    )
